### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by aliffhafiz82** [RobbiNespu/php-mysql-search#2]
i got error 500 with result.php
![Screenshot 2019-11-24 10 03 10](https://user-images.githubusercontent.com/58126060/69488477-a2faeb00-0ea4-11ea-9276-c8ea4c94114f.png)

**Comment by RobbiNespu** [comment]
Salam, skrip ni agak lama tapi masih berfungsi. Error 500 biasa server-side. Cuba check log. Nampak tab pakai cpanel, boleh refer sini https://www.westhost.com/knowledgebase/display/WES/What+Is+A+500+error#:~:targetText=The%20500%20Internal%20Server%20Error,what%20the%20exact%20problem%20is.
